
server: 
  context-path: /im
  port: 7777

datasource: 
  type: com.alibaba.druid.pool.DruidDataSource  
  url: jdbc:mysql://10.9.11.232:3306/fx_db?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: appupload_db
  password: Appupl@ad
  driver-class-name: com.mysql.jdbc.Driver
  minIdle: 1  
  maxActive: 2  
  initialSize: 1  
  timeBetweenEvictionRunsMillis: 3000  
  minEvictableIdleTimeMillis: 300000  
  validationQuery: SELECT 'ZTM' FROM DUAL  
  testWhileIdle: true  
  testOnBorrow: false  
  testOnReturn: false    
  
  
# REDIS (RedisProperties)
spring: 
  redis: 
    database: 1
    host: 10.8.232.205
    port: 6379
    password: tdjgamtam
  pool: 
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
   



