
server: 
  context-path: /starservice
  port: 7777

datasource: 
  type: com.alibaba.druid.pool.DruidDataSource  
  url: jdbc:mysql://10.9.21.225:3306/fx_db?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password: 'Qiao#19810817'
  driver-class-name: com.mysql.jdbc.Driver
  minIdle: 1  
  maxActive: 2  
  initialSize: 1  
  timeBetweenEvictionRunsMillis: 3000  
  minEvictableIdleTimeMillis: 300000  
  validationQuery: SELECT 'ZTM' FROM DUAL  
  testWhileIdle: true  
  testOnBorrow: false  
  testOnReturn: false    
  

# REDIS (RedisProperties)
spring: 
  redis: 
    database: 0
    host: 10.9.21.201
    port: 6379
  pool: 
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0

power:
  server: http://10.9.21.208/authority_service/
  
cluster: 
  zk:
    address: 10.9.21.201:2181,10.9.21.202:2181,10.9.21.203:2181
    product: app_schedule_fxnew
    
#address: 10.9.210.53:2182,10.9.210.54:2182,10.9.210.55:2182
#address: 10.9.210.22:12181
  
  
